# See http://www.appveyor.com/docs/appveyor-yml for many more options
build: off
version: 0.0.{build}

install:
    - ps: Install-Module Pester -Force -Scope CurrentUser
    - ps: Install-Module PSScriptAnalyzer -Force -Scope CurrentUser
    - ps: Install-Module dbatools -Force -Scope CurrentUser

# cache:
# - C:\ProgramData\chocolatey\bin -> appveyor.yml
# - C:\ProgramData\chocolatey\lib -> appveyor.yml
# - C:\Program Files\WindowsPowerShell\Modules\PSScriptAnalyzer -> appveyor.yml
# - C:\Program Files\WindowsPowerShell\Modules\Pester -> appveyor.yml
# - C:\Program Files\WindowsPowerShell\Modules\dbatools -> appveyor.yml

shallow_clone: true

environment:
  environment: master
  version: 0.0.$(appveyor_build_number)

# build_script:
# # grab appveyor lab files and needed requirements for tests in CI
# - ps: .\build\appveyor.prep.ps1
# - ps: .\tests\appveyor.SQL2017.ps1

test_script:
# Test with PowerShell and Pester
- ps: .\build\appveyor.pester.ps1