# This is a basic workflow to help you get started with Actions

name: WindowsCore

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
    branches: [ development ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # # Service containers to run with `runner-job`
    # services:
    #   # Label used to access the service container
    #   redis:
    #     # Docker Hub image
    #     image: mcr.microsoft.com/mssql/server:2019-latest
    #     #
    #     ports:
    #       # Opens tcp port 6379 on the host and service container
    #       - 1433:1433
    #     env:
    #       ACCEPT_EULA: Y
    #       SA_PASSWORD: P@$sw0rdling

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: powershell -c 'Get-Service | Where-Object {$_.name -like ''*MSSQLSERVER*'' -and $_.status -ne ''Running''} | start-service'
    
    - name: Install SQL Express
      run: powershell -F ./Build/Install-SqlExpress.ps1
    
      # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run : |
        cd $ENV:GITHUB_WORKSPACE
        gci 
        pwsh -F ./Tests/Pester.ps1
        